### ISSUE TITLE
Allow buffer as input format

### ISSUE THREAD

**Issue by tuxtof** [Zehir/node-red-contrib-eesmart-d2l#2]
Currently expected input is in Base64 format

possibility to ingest buffer will be a great option

**Comment by Zehir** [comment]
Seems easy to add
Did you want also a setting to have the output in buffer too ?

**Comment by tuxtof** [comment]
no just the input it will be perfect

**Comment by Zehir** [comment]
Par rapport à ce message : https://github.com/Zehir/node-red-contrib-eesmart-d2l/issues/3#issuecomment-727185305
Je pense que ca risque d'être plus compliqué que prévu. Le problème en mettant single buffer c'est qu'il attend que la connexion se ferme avant d'envoyer les données. Le souci c'est qu'on est sensé répondre avant que la connexion se ferme.

Quand tu met `stream of Base64 String` ou `stream of Buffer`, tu as 2 messages qui sont envoyé ?

J'ai fait une demande pour passer en TIC Standard pour pouvoir tester de mon coté. Mais si tu le souhaite on peux faire des tests de ton coté. Contacte moi sur discord Zorimyll#1754

**Comment by Zehir** [comment]
La version 0.2.0 accepte le buffer en plus du base64. Cependant par rapport à l'option single à la place de stream je pense peut poser problème. Je vais faire plus de tests que mon compteur aura changé de format.
