### ISSUE TITLE
Compteur en mode standard

### ISSUE THREAD

**Issue by jpg06** [Zehir/node-red-contrib-eesmart-d2l#3]
Bonjour,
tout d'abord merci pour ce node: j'ai branché le d2l hier, reçu les clés ce matin: ça marche bien 👍 
Pour l'instant mon compteur linky est en mode "historique".
Avez vous testé le d2l avec un compteur en mode "standard" ?

**Comment by Zehir** [comment]
Bonjour,
Non mon compteur est aussi en mode historique, il y a moyen de changer le mode ?

**Comment by jpg06** [comment]
Il faut appeler son fournisseur d'électricité pour demander le changement.
D'après la plaquette commerciale, le D2L devrait fonctionner aussi en mode standard, mais si un utilisateur peut confirmer :)

**Comment by tuxtof** [comment]
je confirme je viens de le faire cette semaine
ca a basculé hier 

j'ai eu un soucis au niveau du TCP in qui segmente le paquet en deux quand il est en output base64 (idem en single ou stream of)
une fois passé en single buffer et avoir réencoder en base64  avant de le passé au node eeSmart tout marche. (d'ou mon ticket #2 pour enlever le reencodage en  base64)

ensuite pas de soucis sur le décodage et j'ai bien beaucoup plus d'info

**Comment by Zehir** [comment]
Je cherche sur l'espace client comment changer mais à première vue je suis obligé d'appeler.
Edit : La procédure décrite [ici](https://forum.gce-electronics.com/t/comment-passer-un-cpt-linky-en-mode-standard/8206/8) semble marcher.

**Comment by jpg06** [comment]
Je viens de le faire par le tchat de mon fournisseur: on verra si ça a fonctionné: enedis doit me recontacter d'ici 5 jours pour confirmation: pourquoi faire simple quand on peu faire compliquée ;)

**Comment by Zehir** [comment]
Quelqu'un as sont compteur en mode standard ? Je pense qu'il peut y avoir un souci si le D2L envoi ses données en plusieurs fois.

**Comment by Zehir** [comment]
Je confirme, cela pose problème mais un nouveau message d'erreur peut arriver si les paquets arrivent en 2 fois. Pour palier le problème il suffit d'ajouter une node join.

**Comment by Zehir** [comment]
Voici un exemple de données en mode TIC Standard :
```json
{
   "_TYPE_TRAME":"STANDARD",
   "_ID_D2L":"02XXXXXXXX9",
   "_DATE_FIRMWARE":"Jul  7 2017",
   "ADSC":"06XXXXXXXX70",
   "VTIC":"02",
   "DATE":"H201120090000",
   "NGTF":"      BASE      ",
   "LTARF":"      BASE      ",
   "EAST":"0XXXXX122",
   "EASF01":"0XXXXX122",
   "EASF02":"000000000",
   "EASF03":"000000000",
   "EASF04":"000000000",
   "EASF05":"000000000",
   "EASF06":"000000000",
   "EASF07":"000000000",
   "EASF08":"000000000",
   "EASF09":"000000000",
   "EASF10":"000000000",
   "EASD01":"0XXXXX111",
   "EASD02":"0XXXXX204",
   "EASD03":"0XXXXX476",
   "EASD04":"0XXXXX331",
   "EAIT":"",
   "ERQ1":"",
   "ERQ2":"",
   "ERQ3":"",
   "ERQ4":"",
   "IRMS1":"002",
   "IRMS2":"",
   "IRMS3":"",
   "URMS1":"238",
   "URMS2":"",
   "URMS3":"",
   "PREF":"06",
   "PCOUP":"06",
   "SINSTS":"00368",
   "SINST1":"",
   "SINST2":"",
   "SINST3":"",
   "SMAXSN":"H20112008|00361",
   "SMAXSN1":"H20111919|01424",
   "SMAXSN2":"|",
   "SMAXSN3":"|",
   "SMAXSN-1":"|",
   "SMAXSN1-1":"|",
   "SMAXSN2-1":"|",
   "SMAXSN3-1":"|",
   "SINSTI":"",
   "SMAXIN":"|",
   "SMAXIN-1":"|",
   "CCASN":"H20112009|00156",
   "CCASN-1":"H20112008|00077",
   "CCAIN":"|",
   "CCAIN-1":"|",
   "UMOY1":"H20112009|239",
   "UMOY2":"|",
   "UMOY3":"|",
   "STGE":"00DAC001",
   "DPM1":"|",
   "FPM1":"|",
   "DPM2":"|",
   "FPM2":"|",
   "DPM3":"|",
   "FPM3":"|",
   "MSG1":"PAS DE          MESSAGE         ",
   "MSG2":"",
   "PRM":"043XXXXXXXX69",
   "RELAIS":"000",
   "NTARF":"01",
   "NJOURF":"00",
   "NJOURF+1":"00",
   "PJOURF+1":"00008001 NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE",
   "PPOINTE":"",
   "_HORLOGE":null
}
```

**Comment by jpg06** [comment]
Bonsoir,

Tous les champs semblent présent en mode standard: c'est un bon point pour le D2L (comparé au mode historique).

Par contre il me semble y avoir une incohérence dans ces valeurs:
"SMAXSN":"H20112008|00361",
"SMAXSN1":"H20111919|01424",

SMAXSN = Puissance app. max. soutirée n 
SMAXSN1 = Puissance app. max. soutirée n phase 1

Tu devrais ne pas avoir de SMAXN1 en compteur monophasé ou au moins avoir la même valeur.
Curieusement, l'horodatage n'est pas le même (ce qui peut expliquer la valeur de puissance différente)



SMAXSN-1  devrait être renseigné aussi.


Le champ date est aussi curieux sauf si tu a prix les valeurs à 9h 00' 00' (c'est possible)
"DATE":"H201120090000",



Tu as appelé directement Enedis ?
Car je suis passé par mon fournisseur, mais pas de changement pour l'instant :-(

**Comment by Zehir** [comment]
A vrais dire j'ai l'impression d'avoir un compteur triphasé avec seulement la phase 1 de branchée...

J'ai envoyé un message à mon fournisseur Total Energie, 24h plus tard ils ont envoyé ma demande au service technique et 48 h après j'étais en TIC Standard

**Comment by tuxtof** [comment]
les compteurs mono et triphasés ont physiquement pas la même tete 

![image](https://user-images.githubusercontent.com/180613/99870387-dd3fbb00-2bd2-11eb-9dd2-51d804f13ee1.png)


pour ma part je suis en tri et les valeurs me semblent bonnes

![image](https://user-images.githubusercontent.com/180613/99870355-b84b4800-2bd2-11eb-977b-ee5ccec8caf9.png)

**Comment by Zehir** [comment]
Je suppose que le petit, comme le mien, c'est le mono ?

**Comment by tuxtof** [comment]
Yep exactement

**Comment by jpg06** [comment]
Bonsoir,
Est-ce normal que l'horodatage des SMAXSN; SMASN1 2 et 3 soit si différents ?
Car on de gros écart:
SMAXSN -> le 21/11/2020 à 02h
SMAXSN1 -> le 20/11/2020 à 12h
SMAXSN2 -> le 21/11/2020 à 00h
SMAXSN 3-> le 21/11/2020 à 02h

Les valeurs d'horodatage  de SMAXSN-1 et suivantes me semblent curieuses aussi.

J'ai raté quelque chose dans le protocole ou le linky ou le d2l chahute un peu ?

**Comment by tuxtof** [comment]
rien n'empêche les SMAXSN  d'être différent

la conso max sur une phase n'a pas lieu obligatoirement au meme moment que la conso max sur la somme des phases

le seul truc bizarre que j'observe chez moi
c'est d'avoir un SMAXSNx supérieur a SMAXSN

et la je me dit que ya un soucis

**Comment by Zehir** [comment]
C'est les données envoyés directement par le Linky, je pense pas que le D2L change les valeurs qu'il recoit

**Comment by jpg06** [comment]
C'est pas évident car normalement le linky devrait envoyer des données plus fréquemment non ?
La c'est toutes les minutes "seulement".

**Comment by tuxtof** [comment]
je mettais pas en cause le D2L, logiquement la fréquence max c'est bien la minute

**Comment by jpg06** [comment]
Je n'ai rien trouvé a ce sujet dans la doc officielle d'enedis (https://www.enedis.fr/sites/default/files/Enedis-NOI-CPT_54E.pdf).

Par contre de nombreux internautes évoquent un envoi de trames toutes les 1 à 2 secondes environs.

**Comment by tuxtof** [comment]
intéressant je pensais pas que cela pouvais descendre en dessous de la minute

**Comment by jpg06** [comment]
Le D2L fait probablement un traitement des données du linky. 
Sinon je ne vois pas en quoi il a besoin qu'on lui renvoie l'horloge en retour.
La sortie TIC du linky n'en a en tout cas aucun besoin.
La doc Du D2L (très succincte) ne parle pas que cette intervale de temps d'une minute soit paramétrable.

**Comment by tuxtof** [comment]
mon interprétation

en mode historique les trame reçu du compteur ne sont pas horodaté, donc il utilise la RTC du module D2L qui se calibre avec les get horloge et les réponses horloge

en mode standard ca ne sert a rien, les trames sont horodaté

**Comment by Zehir** [comment]
Il existe un moyen d'envoyer des commandes au D2L. Sinon à quoi servirait la clé de configuration ? Cependant ça n'est pas documenté

**Comment by jpg06** [comment]
Amha, la clé de configuration doit permettre, si on dispose de la documentation, de se passer de l'application mobile pour la première configuration et la mise à jour du D2L.

**Comment by jpg06** [comment]
> mon interprétation
> 
> en mode historique les trame reçu du compteur ne sont pas horodaté, donc il utilise la RTC du module D2L qui se calibre avec les get horloge et les réponses horloge
> 
> en mode standard ca ne sert a rien, les trames sont horodaté

Hypothèse: cette date/heure du D2l sert si les données sont envoyées vers leur serveur internet pour pouvoir les horodater.
Avec un serveur local, l'intérêt est limité et plus contraignant qu'autre chose (devoir émettre une réponse à chaque fois)

**Comment by Zehir** [comment]
La nouvelle version 1.0.0 permet d'afficher proprement les valeurs de la TIC standard https://github.com/Zehir/node-red-contrib-eesmart-d2l/commit/d851a80822f06043d60c42ef9d3dc396176953f1
