### ISSUE TITLE
Valeurs transmises par le D2L 

### ISSUE THREAD

**Issue by jpg06** [Zehir/node-red-contrib-eesmart-d2l#4]
Actuellement, ces valeurs sont transmises:

**Les champs typiquement D2L**
_TYPE_TRAME, _ID_D2L, , _DATE_FIRMWARE et _HORLOGE

**les champs du Linky renseignés qui me semblent bons**
ADCO, OPTARIF, ISOUSC, IMAX, HCHC, HCHP

**les champs du Linky vides mais c'est normal vu mon abo**
BBRHCJB, BBRHCJR, BBRHCJW, BBRHPJB, BBRHPJR, BBRHPJW, EJPHN, EJPHPM

**les champs vides mais qui devraient peut-être comporté une valeur**
 BASE,  PTEC

**Les champs manquants**
ADPS, IINST, PAPP, HHPHC, MOTDETAT

**les champs qui ne devraient être présent que pour un compteur thriphasé**
ADIR1, ADIR2, ADIR3, IINST1, IINST2, IINST3

Est-ce que vous avez la même chose ?

**Comment by Zehir** [comment]
Quel est le format TIC de ton compteur ? Historique ou Standard ?

**Comment by jpg06** [comment]
Historique

**Comment by Zehir** [comment]
J'ai la même chose sauf que j'ai une valeur BASE, ce qui est la seule valeur qui m'est utile.
```bash
_TYPE_TRAME: "HISTORIQUE"
_ID_D2L: "02XXXXXXXXXX"
_DATE_FIRMWARE: "Jul  7 2017"
ADCO: "06XXXXXXXXXX"
OPTARIF: "BASE"
ISOUSC: "30"
IMAX: "090"
BASE: "XXXXXXX32"
HCHC: ""
HCHP: ""
BBRHCJB: ""
BBRHCJR: ""
BBRHCJW: ""
BBRHPJB: ""
BBRHPJR: ""
BBRHPJW: ""
EJPHN: ""
EJPHPM: ""
_HORLOGE: "2020-11-14T15:42:01.000Z"
PTEC: ""
ADIR1: ""
ADIR2: ""
ADIR3: ""
IINST1: "2"
IINST2: "0"
IINST3: "0"
```

**Comment by Zehir** [comment]
@jpg06 du coup tu as les valeurs que tu souhaite ou pas ?
