### ISSUE TITLE
Cannot read property 'payload' of undefined

### ISSUE THREAD

**Issue by pcatricwattmen** [Zehir/node-red-contrib-eesmart-d2l#5]

**Comment by pcatricwattmen** [comment]
After connecting module D2L as describe in README, the connection seems to be ok, but i have this error 👎 
19 Nov 07:42:13 - [error] [eesmart-d2l:eeSmart D2L] TypeError: Cannot read property 'payload' of undefined

**Comment by Zehir** [comment]
Are you on version 0.2.3?

**Comment by pcatricwattmen** [comment]
yes

**Comment by Zehir** [comment]
Can you post an export of your graph ?
(The keys are removed from the export)

**Comment by Zehir** [comment]
@pcatricwattmen Could you try the version 0.2.4 ? I think I found the bug.
I just push the changes on node-red server, he sould be avaliable in your node-red in 30 min to 1 hour.

**Comment by pcatricwattmen** [comment]
Yes, it's ok now. Thank you.
