### ISSUE TITLE
Pas de communication

### ISSUE THREAD

**Issue by jonathanD91** [Zehir/node-red-contrib-eesmart-d2l#6]
Bonjour, 

Je n'ai pas de communication tcp entre mon module eesmart dans nodered.

**Comment by Zehir** [comment]
Bonjour,

Tu as configuré le D2L via l’application en utilisant serveur local ?
Les deux sont bien dans le même réseau ?
Il n'y as pas de pare-feu entre les deux ?

**Comment by Zehir** [comment]
Vu sur discord, ce problème n'est pas lié au plugin mais au routage des packets TCP depuis le D2L vers une VM puis docker puis node-red
