### ISSUE TITLE
Erreur à la lecture

### ISSUE THREAD

**Issue by JulienEtche** [Zehir/node-red-contrib-eesmart-d2l#7]
Bonjour,

Je rencontre un soucis avec le module. 
Sous le modèle eesmart D2L il est écris: Unkown Playload type, got '1' and expect '3' or '5'. Please open an issue on Github.

Pouvez vous m'aider?
Merci d'avance
Cdt

**Comment by Zehir** [comment]
Bonjour,

Il semblerait que ca soit le même problème que #1.

Le D2L souhaite faire une MAJ ce qui n'est pas possible avec l'api actuel que nous fournit eeSmart.
La seule solution pour le moment c'est de le connecter sur leurs serveurs pendant quelques minutes et ensuite de le reconfigurer en serveur local.

Cordialement;

**Comment by JulienEtche** [comment]
Bonsoir,

Merci pour ce retour rapide. Je vais essayer ça mais pour leur serveur ils m'ont envoyé un lien d'inscription ConsoSpy, c'est leur serveur?
Cdt

**Comment by Zehir** [comment]
Oui exactement, je pense que c'est hébergé chez eux ou alors ils ont délégué, c'est pas très clair

**Comment by Zehir** [comment]
J'ai ajouté un message d'erreur un peu plus précis, il est disponible dans la version 0.2.5 qui devrait être disponible sur node-red d'ici 1h.
