### ISSUE TITLE
Configuration node pour TIC standard

### ISSUE THREAD

**Issue by Yann0128** [Zehir/node-red-contrib-eesmart-d2l#8]
Bonjour,

J’ai réussi à faire fonctionner mon ERL et a récupérer mes infos TIC historique grâce à cet excellent outil et à la procédure ultra détaillée. Merci beaucoup.

Je viens de passer en TIC standard et depuis j’obtiens deux messages d’erreur à chaque connexion TCP : 
- Error : il manque une partie des données, 1460 octets reçu et 1488 attendus.
- Error : assert error : vars.protocolVersion is 3

J’ai vu dans les autres issues qu’il faudrait utiliser un join. Pouvez vous me décrire la manipulation pas à pas ?

Merci par avance.

**Comment by Zehir** [comment]
Bonjour,

Cela arrive quand le paquet envoyé par le D2L est trop gros pour être envoyé en une seule fois.

Il faut ajouter un noeud `join` avant de l'envoyer pour décodage;

![image](https://github.com/Zehir/node-red-contrib-eesmart-d2l/assets/845225/43a97e5e-df46-4b8d-8bd0-d37145bfae8f)
![image](https://github.com/Zehir/node-red-contrib-eesmart-d2l/assets/845225/f7cba60e-10ef-48b2-a174-957054212ac4)

**Comment by Yann0128** [comment]
Un grand merci pour votre aide ! Je récupère la trame entière et je peux maintenant m’amuser à créer plein de sensors 😁
